### ISSUE TITLE
Support for SAP2000 V20,V22,V23

### ISSUE THREAD

**Issue by gib310890** [BHoM/SAP2000_Toolkit#226]
#### Description:

Hi, 

Working with BHoM recently and noticed that the SAP2000 function only support v21?
To the best of my knowledge the DLL files are similar for v20,v22 and v23 and use the same OAPI functions.

I was previously using VBA code to create function in grasshopper with the relevant DLL files.  I find BHoM intutive and would like to contribute to its development.

Thanks
David

**Comment by JosefTaylor** [comment]
Hi David, glad to have you!
the BHoM adapter should support all versions above v21, as CSI has provided a consistently named DLL (SAP2000v1.dll). We're about to test v23, but don't currently have v22 licenses for testing. If you have these versions, please do check if it will attach to them (open SAP2000v22 or v23, turn on the SAP2000_Adapter), and let us know if it works!

SAP2000v20 is unsupported, and we have no plan to support it or older versions (it requires some annoying work, see ETABS_Toolkit for the gymnastics required to support older versions).

**Comment by JosefTaylor** [comment]
Just got access to SAP2000v23 and it does not work, so this is now a priority!

**Comment by JosefTaylor** [comment]
Hi @gib310890, I've created a PR to fix this issue, but I can only test for v23. Would you mind compiling if you're able and testing with v22? Otherwise, wait a couple days for us to close that PR and I'll see if I can generate an alpha installer for you.

**Comment by gib310890** [comment]
Apologies, been busy with relocating myself overseas at the moment with limited access to my PC. 

I wouldn't know how to compile it (I assume compile it in visual basic into a .gh file?).I need a bit of learning to compile it through visual basic. 

If the .gh function is editable in Grasshopper, I can change the .DLL to try if it works.

**Comment by JosefTaylor** [comment]
You'll need Visual Studio, and then you should be able to build the branch on top of your current BHoM installation. There's instructions [here](https://github.com/BHoM/documentation/wiki/Getting-started-for-developers)
Since you've got BHoM installed already you can skip building the base repos and just clone/build this repo.

If you're not comfortable with that, here's a .dll to place in your bhom installation folder, which should be here:

C:\ProgramData\BHoM\Assemblies

[SAP2000_Adapter.zip](https://github.com/BHoM/SAP2000_Toolkit/files/6359413/SAP2000_Adapter.zip)

Extract that file, stick the .dll into the folder above and re-open rhino and grasshopper. It should work! I haven't done it this way for a while, so I'm not certain that will.

As usual, exercise caution when using .dlls you get from strangers on the internet, I'm not responsible if this breaks everything (it shouldn't though)

**Comment by JosefTaylor** [comment]
@BHoMBot check ready-to-merge
