### ISSUE TITLE
Read RigidLinks fails when RigidLinks have no name

### ISSUE THREAD

**Issue by enarhi** [BHoM/SAP2000_Toolkit#254]
#### Description:
Pulling RigidLinks fails as a result of links having no name, which are then added to a dictionary where their key is "" thereby throwing an exception. 

#### Steps to reproduce:
Pull RigidLinks where Rigid Links in SAP2000 have no name.

#### Expected behaviour:
Successful pull, names updated per AdapterId as required.

![image](https://user-images.githubusercontent.com/6752345/151438576-e2287aaa-4f8c-4661-89c8-2c8344e5f8fb.png)

^Value returned by JoinRigidLink method has no name, so the attempt to create a Dictionary that follows throws an exception.

**Comment by JosefTaylor** [comment]
Went in to fix this, but realized this is a bit of a bodge in the question of joining up rigid links that may have been split on the way in. 

- If I use AdapterId instead of the joined name in this dictionary, you can't ask for the original multi-node link you pushed, you instead have to know which id the first of the split links has in SAP.
- If I use Name (as current), you can't ask for one of the split links (i.e. the ID you see in SAP).

So, I think this should be considered in a future effort to clean up the splitting and joining process.

**Comment by enarhi** [comment]
closing as #263 makes this redundant
